INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAGDP1', 'Regional', 'County and MSA gross domestic product (GDP) summary');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAGDP11', 'Regional', 'Contributions to percent change in real GDP');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAGDP2', 'Regional', 'Gross domestic product (GDP) by county and metropolitan area');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAGDP8', 'Regional', 'Chain-type quantity indexes for real GDP by county and metropolitan area (2017=100.0)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAGDP9', 'Regional', 'Real GDP by county and metropolitan area');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC1', 'Regional', 'County and MSA personal income summary: personal income, population, per capita personal income');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC30', 'Regional', 'Economic profile');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC4', 'Regional', 'Personal income by major component');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC5N', 'Regional', 'Personal income by major component and earnings by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC5S', 'Regional', 'Personal income by major component and earnings by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC6N', 'Regional', 'Compensation of employees by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC6S', 'Regional', 'Compensation of employees by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('CAINC91', 'Regional', 'Gross flow of earnings');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('MAIRPD', 'Regional', 'Implicit regional price deflators by MSA');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('MARPI', 'Regional', 'Real personal income by MSA');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('MARPP', 'Regional', 'Regional price parities by MSA');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PAIRPD', 'Regional', 'Implicit regional price deflators by portion');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PARPI', 'Regional', 'Real personal income by portion');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PARPP', 'Regional', 'Regional price parities by portion');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP1-1', 'Regional', 'Gross domestic product (GDP)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP1-2', 'Regional', 'Real GDP');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP1-3', 'Regional', 'Percent change from preceding year in real gross domestic product');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP1-4', 'Regional', 'Contributions to percent change in real GDP');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP2-1', 'Regional', 'Personal consumption expenditures by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP2-2', 'Regional', 'Real personal consumption expenditures by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP2-3', 'Regional', 'Percent change from preceding year in real personal consumption expenditures by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP2-4', 'Regional', 'Contributions to percent change in real PCE');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP3-1', 'Regional', 'Exports and imports of goods and services');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP3-2', 'Regional', 'Real exports and imports of goods and services');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP3-3', 'Regional', 'Percent change from preceding year in real exports and in real imports of goods and services by type of product');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP3-4', 'Regional', 'Contributions to percent change in real exports and imports');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-1-1', 'Regional', 'Gross domestic investment');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-1-2', 'Regional', 'Real gross domestic investment');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-1-3', 'Regional', 'Percent change from preceding year in real gross domestic investment by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-2-1', 'Regional', 'Private fixed investment by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-2-2', 'Regional', 'Real private fixed investment by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-2-3', 'Regional', 'Percent change from preceding year in real private fixed investment by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('PRGDP4-2-4', 'Regional', 'Contributions to percent change in real private fixed investment by type');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACArtsComp', 'Regional', 'ACPSA compensation by ACPSA industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACArtsEmp', 'Regional', 'ACPSA full-time and part-time employment by ACPSA industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACArtsVA', 'Regional', 'ACPSA value added by ACPSA industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACCompLQ', 'Regional', 'Arts compensation location quotient');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACCompRatio', 'Regional', 'Arts compensation ratio');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACEmpLQ', 'Regional', 'Arts employment location quotient');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACEmpRatio', 'Regional', 'Arts employment ratio');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACVALQ', 'Regional', 'Arts value added location quotient');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAACVARatio', 'Regional', 'Arts value added ratio');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP1', 'Regional', 'State annual gross domestic product (GDP) summary');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP11N', 'Regional', 'Contributions to percent change in real GDP');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP2N', 'Regional', 'Gross domestic product (GDP) by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP3N', 'Regional', 'Taxes on production and imports less subsidies');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP4N', 'Regional', 'Compensation of employees');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP5N', 'Regional', 'Subsidies');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP6N', 'Regional', 'Taxes on production and imports');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP7N', 'Regional', 'Gross operating surplus');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP8N', 'Regional', 'Chain-type quantity indexes for real GDP by state (2017=100.0)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAGDP9N', 'Regional', 'Real GDP by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC1', 'Regional', 'State annual personal income summary: personal income, population, per capita personal income');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC30', 'Regional', 'Economic profile');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC35', 'Regional', 'Personal current transfer receipts');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC4', 'Regional', 'Personal income and employment by major component');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC40', 'Regional', 'Property income');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC50', 'Regional', 'Personal current taxes');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC51', 'Regional', 'State annual disposable personal income summary: disposable personal income, population, and per capita disposable personal income');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC5H', 'Regional', 'Personal income by major component and earnings by industry (historical)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC5N', 'Regional', 'Personal income by major component and earnings by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC5S', 'Regional', 'Personal income by major component and earnings by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC6N', 'Regional', 'Compensation of employees by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC6S', 'Regional', 'Compensation of employees by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC70', 'Regional', 'Transactions of state and local government defined benefit pension plans');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC7H', 'Regional', 'Wages and salaries by industry (historical)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC7N', 'Regional', 'Wages and salaries by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC7S', 'Regional', 'Wages and salaries by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAINC91', 'Regional', 'Gross flow of earnings');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAIRPD', 'Regional', 'Implicit regional price deflators by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAOACTVA', 'Regional', 'Outdoor recreation satellite account activities - value added');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAOCOMP', 'Regional', 'Outdoor recreation satellite account compensation');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAOEMP', 'Regional', 'Outdoor recreation satellite account employment');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAOVA', 'Regional', 'Outdoor recreation satellite account value added');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAPCE1', 'Regional', 'Personal consumption expenditures (PCE) by major type of product');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAPCE2', 'Regional', 'Per capita personal consumption expenditures (PCE) by major type of product');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAPCE3', 'Regional', 'Personal consumption expenditures (PCE) by state by type of product');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SAPCE4', 'Regional', 'Personal consumption expenditures (PCE) by state by function');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SARPI', 'Regional', 'Real personal income and real personal consumption expenditures (PCE) by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SARPP', 'Regional', 'Regional price parities by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SASUMMARY', 'Regional', 'State annual summary statistics: personal income, GDP, consumer spending, price indexes, and employment');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQGDP1', 'Regional', 'State quarterly gross domestic product (GDP) summary');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQGDP11', 'Regional', 'Contributions to percent change in real GDP');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQGDP2', 'Regional', 'Gross domestic product (GDP) by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQGDP8', 'Regional', 'Chain-type quantity indexes for real GDP by state (2017=100.0)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQGDP9', 'Regional', 'Real GDP by state');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC1', 'Regional', 'State quarterly personal income summary: personal income, population, per capita personal income');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC35', 'Regional', 'Personal current transfer receipts');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC4', 'Regional', 'Personal income by major component');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC5H', 'Regional', 'Personal income by major component and earnings by industry (historical)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC5N', 'Regional', 'Personal income by major component and earnings by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC5S', 'Regional', 'Personal income by major component and earnings by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC6N', 'Regional', 'Compensation of employees by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC6S', 'Regional', 'Compensation of employees by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC7H', 'Regional', 'Wages and salaries by industry (historical)');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC7N', 'Regional', 'Wages and salaries by NAICS industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('SQINC7S', 'Regional', 'Wages and salaries by SIC industry');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('TASUMMARY1', 'Regional', 'Summary of GDP and components for U.S. territories, current dollars');
INSERT INTO bea_dataset_tables (id, dataset_id, description) VALUES ('TASUMMARY2', 'Regional', 'Summary of real GDP and components for U.S. territories, chained dollars');